### ISSUE TITLE
precompiled aeond freezing on manjaro and becomes unkillable. after computer restart aeond outputs "Bus error (core dumped)" (possibly related to issue #14)

### ISSUE THREAD

**Issue by ghost** [aeonix/aeon#17]
when i started aeond from the command line it starts syncing just like it should. after some time (before fully syncing) it just froze and didn't allow some proccesses to start (the only thing i was able to start was xfce terminal and its commands such as `ls`, starting thunar file manager took forever (more than 10 minutes) and it didn't properly start and by that i mean it was unresponsive) after that happened i restarted the computer and got something like this
`2018-05-27 12:21:28.790	    7fc7caa71bc0	INFO 	global	src/daemon/main.cpp:279	Aeon 'Sophia' (v0.12.0.0-master-release)
2018-05-27 12:21:28.792	    7fc7caa71bc0	INFO 	global	src/daemon/protocol.h:53	Initializing cryptonote protocol...
2018-05-27 12:21:28.792	    7fc7caa71bc0	INFO 	global	src/daemon/protocol.h:58	Cryptonote protocol initialized OK
2018-05-27 12:21:28.793	    7fc7caa71bc0	INFO 	global	src/daemon/p2p.h:63	Initializing p2p server...
2018-05-27 12:21:33.653	    7fc7caa71bc0	INFO 	global	src/daemon/p2p.h:68	p2p server initialized OK
2018-05-27 12:21:33.653	    7fc7caa71bc0	INFO 	global	src/daemon/rpc.h:63	Initializing core RPC server...
2018-05-27 12:21:33.654	    7fc7caa71bc0	INFO 	global	contrib/epee/include/net/http_server_impl_base.h:76	Binding on 127.0.0.1:11181
2018-05-27 12:21:33.654	    7fc7caa71bc0	INFO 	global	src/daemon/rpc.h:69	core RPC server initialized OK on port: 11181
2018-05-27 12:21:33.654	    7fc7caa71bc0	INFO 	global	src/daemon/core.h:86	Initializing core...
2018-05-27 12:21:33.655	    7fc7caa71bc0	INFO 	global	src/cryptonote_core/cryptonote_core.cpp:427	Loading blockchain from folder /home/CENSORED/.aeon/lmdb ...
Bus error (core dumped)
`  
after deleting the lmdb folder it started nomally but had the exact same problem (froze after some time before syncing)  
when i tried to kill the process with the task manager (i opened it before i started aeond) it just didn't work! at one point (after 15 minutes?) task manager reported that itself was using 300% of the cpu. 
when i tried to compile aeon from source i got a compile error which is identical to [this](https://github.com/aeonix/aeon/issues/14#issuecomment-391707867).
from what it looks like it is caused by memcpying a non-trivial class.  
after duckduckgoing i came across [this](https://stackoverflow.com/questions/212466/what-is-a-bus-error) top answer states that bus errors happen when derefrencing a bad pointer so this 2 issues could be related.

**Comment by shigutso** [comment]
What's your hardware? First sync of blockchain uses a lot of CPU and RAM.

Have you tried with a remote node?

**Comment by ghost** [comment]
1) Quad Core Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz with 8 GB of ram.
2) i did not because of security reasons

**Comment by stoffu** [comment]
I've pushed upstream patches in #18 that fixes GCC 8 build errors. Not sure about the freezing and bus error problems. I've installed Manjaro just now and downloaded the release binary to reproduce the issue (on a VM, 2 cores of 2.9 GHz Core i7, 4 GB RAM). So far it's been syncing OK at 141656/960926.

**Comment by ghost** [comment]
[VIDEO.](https://youtu.be/JEUSNjUP4so) please excuse my terrible grammar and pronunciation.  
note that task manager itself was using large amount of cpu while aeond was using 0%

**Comment by stoffu** [comment]
Thanks for the video, it explains the issue quite well. I noticed that you ran aeond with `--block-sync-size 1000 --max-concurrency 15`, which might potentially be the cause of the problem. Can you try running it with no additional flags? The bus error is most likely due to the database being corrupt after hard shutdown.

Also, can you check if you can reproduce the same with Monero?

**Comment by ghost** [comment]
ok tested aeond without arguments still having the same issue.
gonna try compiling aeon from source with your changes
edit: couldn't get aeon to compile still getting the same error
gonna try with monero now

**Comment by stoffu** [comment]
FWIW the release daemon synced fine on my Manjaro desktop installed on a VM.

**Comment by ghost** [comment]
ok i tried syncing monero. at first it was doing great but then it froze for about 5 minutes and then syncing became realy slow.
this is what i found in the bitmonero.log
`2018-05-28 12:42:20.870	[P2P9]	TRACE	blockchain.db.lmdb	src/blockchain_db/lmdb/db_lmdb.cpp:1830	BlockchainLMDB::get_block_timestamp
2018-05-28 12:48:25.325	[P2P8]	TRACE	net.throttle	contrib/epee/src/network_throttle-detail.cpp:218	Throttle throttle_speed_in: packet of ~1440b  (from 1440 b) Speed AVG=  15[w=9.834]   15[w=9.834] /  Limit=16 KiB/sec  [27360 28264 27360 31680 46080 1473 0 0 0 0 ]
2018-05-28 12:48:25.463	[P2P7]	TRACE	blockchain	src/cryptonote_core/blockchain.cpp:320	Blockchain::get_current_blockchain_height`

**Comment by stoffu** [comment]
Then please open a new ticket under Monero so that the issue gets more exposure.

**Comment by ghost** [comment]
so i got compiled the deamon from aur and it's working without any problems! huge thanks to everyone for taking your time
